config/routes.rb
TagrServer::Application.routes.draw do

  resources :tag_images

  post 'signup', to: 'users#create'
  post 'login', to: 'api_keys#create'
  

end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base

  before_create :generate_access_token

  attr_accessible :access_token, :user

  belongs_to :user

  private

  def generate_access_token
    begin
      self.access_token = SecureRandom.hex
    end while self.class.exists?(access_token: access_token)
  end

end

app/models/tag_image.rb
class TagImage < ActiveRecord::Base

  attr_accessible :image

  has_and_belongs_to_many :users

  mount_uploader :image, TagImageUploader

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  attr_accessible :email, :password, :password_confirmation

  validates_presence_of :email
  validates_uniqueness_of :email

  has_many :api_keys, :dependent => :destroy
  has_and_belongs_to_many :tag_images

  def ensure_api_key
    if api_keys.empty?
      reset_api_keys
    end
  end

  def reset_api_keys
    api_keys.delete_all
    api_keys << ApiKey.create
  end

end

app/controllers/api_keys_controller.rb
class ApiKeysController < ApplicationController

  skip_before_filter :verify_api_key

  respond_to :json

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      user.ensure_api_key
      flash[:success] = "Logged in!"
    else
      flash[:error] = "Email or password is invalid"
    end
    respond_with user do |format|
      format.json { render json: user.api_keys.first.to_json(only: :access_token) }
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_filter :verify_api_key
  after_filter :flash_to_headers

  def flash_to_headers
    if !flash[:error].blank?
      response.headers['X-Message'] = flash[:error]
      response.headers['X-Message-Type'] = "error"
    elsif !flash[:notice].blank?
      response.headers['X-Message'] = flash[:notice]
      response.headers['X-Message-Type'] = "notice"
    elsif !flash[:success].blank?
      response.headers['X-Message'] = flash[:success]
      response.headers['X-Message-Type'] = "success"
    end
    flash.discard
  end

  private

  def current_user
    access_token = params[:api_key]
    return nil unless !access_token.nil?
    api_key = ApiKey.find_by_access_token(access_token) 
    return nil unless !api_key.nil? 
    @current_user ||= User.find(api_key.user_id)
  end
  helper_method :current_user

  def verify_api_key
    head :unauthorized if current_user.nil?
  end

end

app/controllers/tag_images_controller.rb
class TagImagesController < ApplicationController

  respond_to :json

  def index
    Rails.logger.debug "Entering index action"
    Rails.logger.debug "current_user.id = #{current_user.id}"
    @tag_images = current_user.tag_images
    respond_with @tag_images, location: nil
  end

  def show
    @tag_image = TagImage.find(params[:id])
    respond_with @tag_image, location: nil
  end

  def create

    tag_image = params[:tag_image]

    stringio = TagImageStringIO.new(Base64.decode64(tag_image[:image]))
    stringio.original_filename = tag_image[:filename]

    @tag_image = TagImage.new
    @tag_image.image = stringio

    if @tag_image.save
      flash[:notice] = 'Tag image was successfully created.'
    else
      flash[:error] = @tag_image.errors
    end

    respond_with @tag_image, location: nil

  end

  def update

    tag_image = params[:tag_image]

    @tag_image = TagImage.find(params[:id])

    stringio = TagImageStringIO.new(Base64.decode64(tag_image[:image]))
    stringio.original_filename = tag_image[:filename]

    @tag_image.image = stringio

    if @tag_image.save
      Rails.logger.debug "update save succeeded"
      flash[:notice] = 'Tag image was successfully updated.'
    else
      flash[:error] = @tag_image.errors
    end

    head :no_content

  end

  def destroy
    @tag_image = TagImage.find(params[:id])
    @tag_image.destroy
    head :no_content
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter :verify_api_key

  respond_to :json

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "User created"
    else
      flash[:error] = "User creation failed"
    end
    respond_with @user, :location => nil
  end

end

app/helpers/api_key_helper.rb
module ApiKeyHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tag_images_helper.rb
module TagImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TagrServer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tag_images/_form.html.erb
<%= form_for(@tag_image) do |f| %>
  <% if @tag_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag_image.errors.count, "error") %> prohibited this tag_image from being saved:</h2>

      <ul>
      <% @tag_image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tag_images/edit.html.erb
<h1>Editing tag_image</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag_image %> |
<%= link_to 'Back', tag_images_path %>

app/views/tag_images/index.html.erb
<h1>Listing tag_images</h1>

<table>
  <tr>
    <th>Image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tag_images.each do |tag_image| %>
  <tr>
    <td><%= tag_image.image %></td>
    <td><%= link_to 'Show', tag_image %></td>
    <td><%= link_to 'Edit', edit_tag_image_path(tag_image) %></td>
    <td><%= link_to 'Destroy', tag_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tag image', new_tag_image_path %>

app/views/tag_images/new.html.erb
<h1>New tag_image</h1>

<%= render 'form' %>

<%= link_to 'Back', tag_images_path %>

app/views/tag_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Image:</b>
  <%= @tag_image.image %>
</p>


<%= link_to 'Edit', edit_tag_image_path(@tag_image) %> |
<%= link_to 'Back', tag_images_path %>